### ISSUE TITLE
early stop / zero instances

### ISSUE THREAD

**Issue by sronilsson** [murthylab/sleap#348]
SLEAP is absolutely stunning! I'm following along tutorial and I keep getting an Early_stop after max 20 iterations, I've got about 70 labeled images, and always 0 instances found. I've tried to predict on 20 random or entire video. I'm using the top-down setting and centroid anchor points. I've poked around and can't find the early stopping parameters in the GUI? I was hoping changing/removing this could help me. Or if you have advice on any other issue that commonly cause this it would be very helpful. Thank you!

**Comment by talmo** [comment]
Hi Simon,

This could really be an issue stemming from a number of sources, but let's go with the simplest solution of just training longer.

We'll add that to the GUI since it probably will be more convenient to be able to tune it from there (#349), but in the meantime you can set this yourself by editing the training job configuration generated from the last training job.

Simply go in the `models/` subfolder in your labels directory, open the latest run folder that was created there, and copy/modify the `initial_config.json` that was generated. You can scroll down to the `"optimization": { ... "early_stopping": { ... }` section to increase the patience and cooldown parameters. [See here](https://github.com/murthylab/sleap/blob/21b84fe42a7727ccdc23d5827ed1dbad93ef053f/sleap/nn/config/optimization.py#L135-L151) for more details on the behavior of those specific configurations.

Once you've saved that job configuration file, you can just select it from the GUI within the _Run Training..._ window.

As a more general tip, I'd recommend monitoring the training progress to ensure that you're seeing improvements in the loss and enabling the visualizations to get a qualitative sense of how the training is going.

Let us know if you're still having issues, otherwise we'll close this after a little while.

**Comment by ntabris** [comment]
Early stopping params are shown in the GUI in SLEAP v1.0.2 (now on PyPI and anaconda).

**Comment by sronilsson** [comment]
Thanks you very much @ntabris and @talmo -  it works well in the GUI now
