### ISSUE TITLE
Errors during training not caught

### ISSUE THREAD

**Issue by ntabris** [murthylab/sleap#365]
Error during training, stopped updating monitor and printed this message in terminal:

```
Epoch 00013: early stopping
2020-06-17 16:46:34.480694: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
INFO:sleap.nn.training:Finished training loop. [15.9 min]
```

but otherwise no indication that something had gone wrong.

**Comment by talmo** [comment]
That line is a common warning that happens due to batching not dividing equally into the number of samples. It's not a problem since the iterator resets after each epoch.

I'm not sure about the monitor though -- does ZMQ block the socket?
Can training restart?
Any OOM messages?

This message will probably go away when we update to TF 2.2 (#345), but doesn't address the issue.
