### ISSUE TITLE
Error when running inference after training on all labeled frames vs. random frames

### ISSUE THREAD

**Issue by Idavr** [murthylab/sleap#374]
Hi!

I have no problems running the training of a model multiple times on random (200) frames, nor with the automatic inference that runs immediately after on all videos, but when I try to do the exact same thing - only on all labeled frames (600-700 now) - I run into this problem after the models have been trained:

System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
Traceback (most recent call last):
  File "c:\users\idavalik\appdata\local\continuum\anaconda3\envs\sleap_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\idavalik\appdata\local\continuum\anaconda3\envs\sleap_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\sleap_env\Scripts\sleap-track.exe\__main__.py", line 7, in <module>
  File "c:\users\idavalik\appdata\local\continuum\anaconda3\envs\sleap_env\lib\site-packages\sleap\nn\inference.py", line 1264, in main
    video_readers = make_video_readers_from_cli(args)
  File "c:\users\idavalik\appdata\local\continuum\anaconda3\envs\sleap_env\lib\site-packages\sleap\nn\inference.py", line 1109, in make_video_readers_from_cli
    filename=args.video_path, example_indices=args.frames, **video_kwargs
  File "c:\users\idavalik\appdata\local\continuum\anaconda3\envs\sleap_env\lib\site-packages\sleap\nn\data\providers.py", line 234, in from_filepath
    video = sleap.Video.from_filename(filename, **kwargs)
  File "c:\users\idavalik\appdata\local\continuum\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\video.py", line 1136, in from_filename
    raise ValueError("Could not detect backend for specified filename.")
ValueError: Could not detect backend for specified filename.
Process return code: 1

It happens when the system tries to run inference on the very first video, and from the Error there seems to be some problems in finding said video. However, what makes me scratch my head is why this does not happen when running training+inference on "Random frames"?

**Comment by talmo** [comment]
Hi @Idavr,

Do you get the same error when you go to the GUI menu **Predict** -> **Run Inference**... -> **Predict on** -> **user labeled frames**?

**Comment by Idavr** [comment]
Hi,

No, I did not... Is it not the same process?

**Comment by talmo** [comment]
It should be! Looks like a bug. Thanks for reporting it, we had a hard time tracking this problem down last time it came up. We'll work on a patch for the next version.

In the meantime, as a workaround you should be OK if you just don't predict together with the training, and do it through the Run Inference dialog afterwards.

**Comment by Idavr** [comment]
Puh, alright, good to know it is still workable then!

So, it is ok for me to press the Run Training option and let it stop itself at the Inference-stage, and then just Run Inference manually? Or is there a way to only train without the subsequent automatic Inference?

Also, going through it again it looks like it only ran inference on one video, is this normal when running that step manually? I also got some OOM error messages, so that could be the reason for that (did not get that during the automatic Inference step).

**Comment by talmo** [comment]
Yeah, if it errors out during automatic inference, you can just ignore it and run it manually. Restart SLEAP if you run into problems. You can also skip automatic inference after training by selecting this option in the training configuration window:
![image](https://user-images.githubusercontent.com/3187454/86479898-faa2e400-bd1a-11ea-9e59-bdbc5e3e03c4.png)

Hmm, if you selected **user labeled frames** and you have labeled frames in more than one video, it should definitely have run on all of them. What do you get in the dialog that pops up at the end that says how many frames/instances were predicted?

The OOM messages are just warnings. If your GPU had more memory it might have run faster, but if your computer didn't freeze up it means you can safely ignore them :)

**Comment by Idavr** [comment]
Ah, ok! An easy workaround then, thank you :) 

Sorry, my bad, going back through the code it does indeed seem like it ran on all videos (gives 10 lines of "predicted frames" information, and the dialog pop-up did say all 600+ frames were predicted with 0 frames with 0 instances found. I was just confused since it took comparatively way shorter time than when I have run the Training + Inference so I only managed to see the progress bar for one video.

**Comment by ntabris** [comment]
Hi, @Idavr. Could you tell me the filename of your video(s)? I think our code might be having trouble figuring out the filetype based on the filename + ext.

**Comment by Idavr** [comment]
Hi @ntabris. They follow the same template in the form of either (as two examples) "Exp13-1.mp4" or "Experiment7-1.mp4".

**Comment by ntabris** [comment]
Thanks! Hm... okay, that should be fine. If you don't mind doing one more thing for me, could you try using the settings in "Run Training…" that cause a problem, but instead of clicking "Run" click "Save configuration files…". You'll tell it where to save the files (maybe make a new directory for them to all go in). It will create a file called `inference-script.sh`. Could you upload that file (or email it to tabris@princeton.edu)? That should help me figure out where something is going wrong.

**Comment by Idavr** [comment]
Sent you an e-mail now.

**Comment by ntabris** [comment]
Bug fixed in SLEAP v1.0.6 (currently being pushed/deployed).

(Thanks again for your help, @Idavr!)

**Comment by alexkiani** [comment]
Hi, 

I was able to run training and the automatic inference on both random frames and labelled frames. However, when I try to run inference alone for either random frames or labelled frames, I get a similar error message. 

![Screen Shot 2020-07-07 at 2 15 49 PM](https://user-images.githubusercontent.com/30673344/86847142-bab46780-c060-11ea-89ec-ba8de5367725.png)

**Comment by ntabris** [comment]
Hi, @alexkiani. I wasn't able to replicate the problem you're having. When inference starts running, it prints the command line call to your terminal (`Command line call: sleap-track`... up until `Namespace`). If you're still having the problem could you share that command-line call?

Also, are you trying to use tracking when running inference on random/labelled frames? It doesn't really work to do this since the tracker assumes it's running on a contiguous range of frames (we should probably make this clearer in the GUI/docs).

**Comment by ntabris** [comment]
(Oh, just to check, what version of SLEAP are you using? The version number is shown in the window titles in the GUI.)

**Comment by alexkiani** [comment]
Sorry for the delay! The version that I am using is 1.0.6. I kind of realized that tracking might only work on continuous frames. Tho I am not sure if this means that I would only be able to run tracking if I first run inferences on the entire video, since it does not seem to allow me to generate continuous suggested frames. 

![Screen Shot 2020-07-17 at 11 57 43 AM](https://user-images.githubusercontent.com/30673344/87821956-88a3c200-c825-11ea-8936-b1591586fa39.png)
