### ISSUE TITLE
Can't save and load labels with NumpyVideo

### ISSUE THREAD

**Issue by iteal** [murthylab/sleap#408]
Hi!

I use the NumpyVideo class for my videos as they are already in memory, to avoid saving them to a file.
I am trying to save and load my labels as a slp file, but it is not implemented for raw numpy videos.

I want to test different tracking methods and parameters without having to predict my whole video each time, that's why I am trying to save the Labels. I can't use pickle with this Labels class either (max recursion!) so I thought I could use the save and load_file functions.

I use sleap version 1.0.9.

Here is a reproducible example:

```python
import numpy as np

from sleap import Video, Labels
from sleap.instance import LabeledFrame

# create dummy video in a numpy array
numpy_frames = np.zeros((1, 20, 20, 1), dtype=np.uint8)

# save the video to a file
np.save("numpy_video.npy", numpy_frames)

#OK: save and load labels using the numpy video filename
labels = Labels([LabeledFrame(video=Video.from_numpy("numpy_video.npy"), frame_idx=0)])
labels.save("numpy_vid.slp")
Labels.load_file("numpy_vid.slp")

#BUG: save and load labels using directly the numpy video
# FileNotFoundError: Could not find filename Raw Video Data
labels = Labels([LabeledFrame(video=Video.from_numpy(numpy_frames), frame_idx=0)])
labels.save("numpy_vid.slp")
Labels.load_file("numpy_vid.slp")
```

What do you think?

**Comment by talmo** [comment]
Hi @iteal,

Right, the problem here is that from numpy arrays in memory we don't have a filepath to point to for loading it back in later.

You could either point to the real (original) data using the appropriate backend (e.g., `MediaVideo`) or you could try to use `DummyVideo` as a placeholder, like this:

```python
from sleap import Video, Labels
from sleap.instance import LabeledFrame
from sleap.io.video import DummyVideo

vid = Video(backend=DummyVideo("video0", 1, 20, 20, 1))
labels = Labels([LabeledFrame(video=vid, frame_idx=0)])
labels.save("dummy.slp")
labels_ = sleap.load_file("dummy.slp")
```

Note that this will not actually use the images you have in memory, but it serves to enable saving/loading when you don't want to specify the video metadata directly.

Let me know if that works for you or if there's something else you had in mind.

**Comment by iteal** [comment]
Thanks there is a workaround indeed!
Maybe the error message should be more clear to understand what is going on?
