### ISSUE TITLE
Evaluate Metrics for Trained Models…

### ISSUE THREAD

**Issue by vcorbit** [murthylab/sleap#409]
How do I use the function "Evaluate Metrics for Trained Models…" in the Predict menu? When I open it, I see all the models I've trained, and it tells me how many frames were used for training and validation, but none of the metrics for evaluation are filled in. When I click "View Metrics", it says "Metrics have not been generated for this model". Is there something I need to turn on in order to generate these values for my trained models? 

Thanks!

**Comment by talmo** [comment]
Closing this old issue since it was a result of the older SLEAP versions that didn't generate metrics after training.

For reference, now you can just go to **Predict** -> **Evaluation Metrics for Trained Models...** to visualize model metrics for models with `metrics.train.npz` and `metrics.val.npz` in their folder.
