### ISSUE TITLE
How to continue training a trained model?

### ISSUE THREAD

**Issue by SamMinkowicz** [murthylab/sleap#482]
How can I continue training a trained sleap model?

Thanks!
Sam

**Comment by talmo** [comment]
Hi @SamMinkowicz,

Sorry for the delay! I've been swamped with a major deadline.

This is a tricky one from the GUI since we do a lot when we assume the training is done, but you can definitely achieve this with no problems if you're running SLEAP interactively.

It roughly looks like this (in SLEAP v1.1.x):
```py
# Load config.
cfg = sleap.load_config("models/my_model")

# Create and initialize the trainer.
trainer = sleap.nn.training.Trainer.from_config(cfg)
trainer.setup()

# Replace the randomly initialized weights with the saved weights.
trainer.keras_model.load_weights("models/my_model/best_model.h5")

# Train for 10 epochs.
trainer.config.optimization.epochs = 10
trainer.train()
```

And here's an example notebook demonstrating this:
https://colab.research.google.com/drive/1MRELpNY-HkN--h7ixlo04A9iOGRNlmor?usp=sharing

This could be a more easily accessible feature in the future -- let me know if you have any feedback or suggestions based on the way you'd be using it.

Cheers,

Talmo

**Comment by SamMinkowicz** [comment]
Hi @talmo,

No worries! 

Thanks for your super helpful reply! I'll let you know if I have any suggestions.

Best,
Sam
