### ISSUE TITLE
How to retrieve confidence score data

### ISSUE THREAD

**Issue by Xiaoyu-Tong** [murthylab/sleap#521]
Hi,

Again, thank you for developing such an interactive GUI.

As I play with the exported data (h5 files), I found that only "node_names", 'track_names', 'track_occupancy' and 'tracks' are stored in the h5 file. Actually I am pretty interested in the data of confidence score and I may use those scores to perform some post-processing. Is there anyway to retrieve the confidence score data? I am OK to extract the data if you can advise me how data are stored in the .slp file, or it would be awesome that you could add the confidence store to the exported h5 file. By the way, I noticed that in some rare cases, the confidence score can be greater than 1 (I have observed score=1.05). Sorry I may have missed it, but what is the definition of confidence score in your framework and how it would be interpreted if it has a value >1?

Thank you!

**Comment by talmo** [comment]
Hi @Xiaoyu-Tong,

Yeah so that's a bit tricky -- we opted to just keep the points when exporting since there's lots of scores you could use and they end up taking a lot of space.

Anyhow, here's a Colab notebook showing you how to build similar arrays "by hand":
https://colab.research.google.com/drive/1F0IxV6nmXiOSwM9UEbaEjPRPca_NEafH?usp=sharing
It goes from video to tracking to compiling the results in numpy arrays, but you could use similar logic to create your desired outputs from a saved predictions file.

As for why it can sometimes be above 1: that depends on the model type, but generally speaking we don't constrain confidence map models to explicitly output values in the [0, 1] range -- we just train them to do that. This means that it might go slightly over 1 or below 0 sometimes, but you can just clip it to the expected range if you need. The interpretation is the same (0 = bad, 1 = good).

It'd be nice to add a feature like this from the GUI in the future, so I'm tagging this as an enhancement.

Let me know if you have any questions!

Talmo

**Comment by Xiaoyu-Tong** [comment]
Hi @talmo ,

Sorry but I did not find a way to reopen the issue, so I am replying here for issue 517 (size issue for topdown centroid model). I just want to let you know in case you are unaware that sleap v 1.1.2 is not yet available for installing/upgrading. Neither pip install in local anaconda prompt nor on Google Colab could find the version 1.1.2.

**Comment by Xiaoyu-Tong** [comment]
Update: I can use v1.1.2 now!

**Comment by talmo** [comment]
Sorry about that @Xiaoyu-Tong! Had a little glitch with our automated build system so I had to go in and do it manually. Glad to hear you got it installing now :)
