### ISSUE TITLE
Error training centered_instance unet model with corrected predictions

### ISSUE THREAD

**Issue by SamMinkowicz** [murthylab/sleap#537]
Hi, I am attempting to train a model and am getting `TypeError: Cannot iterate over a Tensor with unknown first dimension.` The full log is in [sleap_error.txt](https://github.com/murthylab/sleap/files/6250434/sleap_error.txt). I originally imported a DLC labeled dataset and trained the same model. I then ran predictions, edited a bunch of frames, and exported a new training package with these edited frames. I sent an email to sleap@princeton.edu with a link to the training package. The config file is: [centered_instance.txt](https://github.com/murthylab/sleap/files/6250419/centered_instance.txt)

I'm using v1.1.3 for training.

Thanks for your help!
Sam

**Comment by talmo** [comment]
Hey @SamMinkowicz,

Apologies for the long delay! Just getting back into this and wanted to touch base with you before digging further.

It seems like there were a couple of problems with the labels you sent me.

First, there were multiple skeletons (@ariematsliah-princeton). This typically happens as a result of merging or importing from DLC and then modifying the skeleton. I think this is necessary, but depending on your workflow can result in duplicates or more.

This issue has a relatively easy patch in your case since the skeletons are identical except for added edges:
```py
import sleap
import numpy as np

labels = sleap.load_file("padded2.pkg.slp")

bad_skeleton = labels.skeletons[0]
good_skeleton = labels.skeletons[1]
labels.skeletons = [good_skeleton]

for lf in labels:
    for i, inst in enumerate(lf.instances):
        if inst.skeleton == bad_skeleton:
            if type(inst) == sleap.Instance:
                new_inst = sleap.Instance.from_numpy(inst.numpy(), skeleton=good_skeleton, track=inst.track)
            elif type(inst) == sleap.PredictedInstance:
                new_inst = sleap.PredictedInstance.from_numpy(inst.numpy(), point_confidences=inst.scores, instance_score=inst.score, skeleton=good_skeleton, track=inst.track)
            lf.instances[i] = new_inst

labels.save("padded2.fixed.pkg.slp", with_images=True)
```

The second issue is a little trickier and has to do with #463: some of the videos are grayscale, while others are RGB.

This is a bit trickier to fix in the exported package, but if you send us the original .slp labels file (`sleap@princeton.edu`), we can try to work a similar patch into it.

@ariematsliah-princeton: For the future, I think we need to add some better validation of RGB/grayscale when importing DLC data and ideally a way manually edit the RGB/grayscale flag per video.


@SamMinkowicz: An alternative workaround, albeit painful, would be to create a new SLEAP project and import the original video files on their own instead of importing stuff, and making sure everything is set the grayscale. Happy to help with writing a little importer if it helps!

**Comment by SamMinkowicz** [comment]
Hey @talmo,

Now my apologies for the long delay! I decided to go another route with this dataset and am updating my setup to enable 3d tracking. I'm okay just closing this issue unless you think the solution would help others and then I would be happy to see it through.

Best,
Sam

**Comment by talmo** [comment]
No worries -- cheers!
