### ISSUE TITLE
ID swapping during tracking

### ISSUE THREAD

**Issue by talmo** [murthylab/sleap#544]
Hi folks, I found this thread while also struggling with some swapped identity issues with SLEAPv1.1.3. I implemented the above suggestions on a bottom up model trained on two mice freely interacting (lots of following and circling behavior, so likely a similar situation to @sronilsson ), and I immediately noticed an improvement in maintaining track identities when the mice were circling each other, which previously had been a major source of swapped identities. 

However, the identities are still commonly swapped when the two mice are following each other in a straight line, especially when one mouse is about 10-20 frames behind the first mouse and following in the path/track of the first mouse. Fortunately, these can be fairly easily identified by using velocity suggestions, but in a 15 minute video I am still getting something on the order of >100 swaps. I have experimented with increasing the tracking window from 20 to 60 frames, but this seems to have made the issue worse. I had bumped it to 20 following the suggestions outlined above, but perhaps dropping it back down to 5 would be best? 

Please let me know if you have any suggestions re: altering the training/inference parameters that might help here!

I've emailed my exported training package to you @talmo, thanks in advance for your help here. Happy to share other  project details if needed.

_Originally posted by @calebvogt in https://github.com/murthylab/sleap/issues/362#issuecomment-826850107_

**Comment by talmo** [comment]
Hi @calebvogt,

Have you tried using the `flow` tracker? This uses flow shifting to update predicted locations across frames. In addition to updating the location of the animals to improve the track matching.

You'll also, as you have already begun to try, want to reduce the tracking window as much as possible, ideally to around ~5 frames, so you reduce the chance of ambiguity due to overlapping tracks during chases for example.

If that's getting you close but not quite there, you can try using the Kalman filter tracker (set [`--tracking.kf_init_frame_count`](https://sleap.ai/guides/cli.html#inference-and-tracking) to a value >1), which we use to model motion of individual body parts a little more robustly.

If your animals are sufficiently visually distinct, we can also try a beta feature which enables ID tracking via visual classification.


Let me know if you've tried any of these and which ones we can help with!

Cheers,

Talmo

**Comment by calebvogt** [comment]
Hey @talmo, apologies for the delayed response. In my above response to the previous thread, I had implemented the flow tracker which did provide a dramatic improvement over the simple tracker in maintaining identities of two mice when they were circling. As you indicated above, I dropped the tracking window down to 5 and that has also led to a dramatic improvement to what I had before. I have not yet tried using the kalman filter, but may do so in the future to get further improvements. 

My current filming environment is on two animals that are visually similar, but I do have other data sets that have distinct visual features that the beta feature might be a good fit for. However, ill try some of these other tactics before trying that out. 

For other folks coming across this thread, I am using the following script to batch process videos of two similar mice interacting freely in a small open field chamber using a multi-animal bottom up trained model. The following arguments for me are working quite well (with fairly minimal id swaps). I get some swaps when mice are directly following each other (nose to tail). In order to reduce that further, I may drop the tracking window to ~2-3 frames and/or implement the kalman filter tracker as suggested above. Note that the speed is fairly slow on a 2080ti I7 processor, around ~5-10fps, but I am running inference and across frame tracking simultaneously. 

import os
import subprocess

subprocess.call('(for %i in (*.mp4) do sleap-track ''%i'' -m "SLEAP_v2/models/MOSH_210425_114606.multi_instance.n=207" --no-empty-frames --tracking.tracker flow --tracking.target_instance_count 2 --tracking.pre_cull_to_target 2 --tracking.pre_cull_iou_threshold 0.9 --tracking.post_connect_single_breaks 2 --tracking.clean_instance_count 2 --tracking.similarity instance --tracking.match greedy --tracking.track_window 5)', shell=True)

**Comment by talmo** [comment]
Hi @calebvogt,

Good to hear you've been able to see an improvement!

Regarding performance: Yeah, the flow tracker can be a little slow so it's the bottleneck, but you might be able to squeeze out a few more FPS by increasing the batch size with `--batch_size 32` (default is 4 for low memory GPUs).

I'll go ahead and close this thread but feel free to comment if you're still running into issues.

Cheers!

Talmo
