### ISSUE TITLE
CUDA driver problem

### ISSUE THREAD

**Issue by jckittell** [murthylab/sleap#551]
Just updated to 1.1.3 on Windows, and the anaconda prompt is throwing an error when I attempt an inference using a preexisting training set: CUDA driver version is insufficient for CUDA runtime version. I tried updating the CUDA driver via Nvidia's exe, and restarted the computer. No change. Is there a way to fix this via conda?

**Comment by ariematsliah-princeton** [comment]
Hi @jckittell 
I believe this means driver version must be at least your CUDA Toolkit version.

To make sure this is related to SLEAP version update (and not something unrelated), can you please reinstall the previous version of SLEAP in a separate conda environment and check if you still get this error? If so, what is the version of SLEAP that works? Then we can narrow down the search for the root cause.

Thanks

**Comment by jckittell** [comment]
Reinstall fixed it, not sure what happened. Email incoming, I have a usage question. Thanks!
