### ISSUE TITLE
small noise in predicted positions

### ISSUE THREAD

**Issue by smidm** [murthylab/sleap#552]
I've encountered an interesting pattern in the predicted xy positions. The positions are quantized to a grid (probably) due to the `output_stride` option https://sleap.ai/api/sleap.nn.config.model.html?highlight=unet#sleap.nn.config.model.CentroidsHeadConfig.output_stride. 

There is also a small noise added to the coordinates. What is the source of the noise?

This is not a serious issue that is constraining my workflow. I'm just curious where is the noise coming from and I want to share the issue with other users wondering what's happening with the predicted data.

Also a question on the quantization: can I get rid of that just by setting `output_stride` to 0? Are there any side effects other than slower inference and GPU memory requirements?

![xy positions of a single keypoint](https://user-images.githubusercontent.com/820292/118078630-e73ebb80-b3b6-11eb-8634-1905870318d2.png)
![xy positions of a single keypoint](https://user-images.githubusercontent.com/820292/118078668-f6be0480-b3b6-11eb-8363-36d3818e0881.png)
![xy positions of a single keypoint](https://user-images.githubusercontent.com/820292/118078693-02a9c680-b3b7-11eb-8745-362a9559bad2.png)

used code:

```
import h5py
f = h5py.File('data/HH1_crf17_pre.mp4.analysis.h5', 'r')  # exported analysis, File -> Export Analysis HDF5
tracks_matrix = f['tracks'][:]
df = pd.DataFrame(tracks_matrix[0, :, 1, :].T, columns=['x', 'y'])
df.plot.scatter('x', 'y', s=2)
plt.gca().set_aspect('equal', adjustable='box')
```

**Comment by talmo** [comment]
Hey @smidm,

Yup, this happens because we use confidence maps to predict keypoint locations and the output stride controls their resolution. We actually do subpixel refinement on those, but there's still some hard limits on how precise we can be based on the size of the grid and the sigma.

You'll get the best results by having the lowest output stride (= 1) and sigma (recommended: 1.5 or 2.0) to minimize these discretization artifacts. The trade-off is that output stride of 1 is slow, and low sigmas may be harder to train, but if you have a working model, you can try pushing in those directions.

Let me know if you get a chance to try it out, will be curious to see what you get :)

**Comment by mparteagaa** [comment]
I was doing a heatmap of all trajectories by rounding the coordinates (per pixel) of one subject and obtained the same.
![heatmap1](https://user-images.githubusercontent.com/60982483/155121596-613c6da6-3236-4c0f-bd76-fa348eba9f3e.png)

This how the matrix looks like: 
![heatmapmat1](https://user-images.githubusercontent.com/60982483/155122142-a5465538-1f6b-45f4-8562-cef2a36968b0.PNG)

**Comment by talmo** [comment]
Hi @mparteagaa,

Yep, this is known as _quantization error_ and happens as a result of using lower resolution confidence maps than the image. This is done for both speed and memory savings since we might have many heatmaps and potentially very large images.

We attempt to compensate for this by using subpixel refinement, but that will only really work if you have a small enough sigma. I recommend trying to train the model with sigma = 2.5 or 1.5. The smaller the value, the better subpixel resolution, but the harder it might be to train.

The alternative, which is only amenable if you have a GPU with sufficient memory, is to decrease the output stride of the confidence maps to increase their resolution. Usually an output stride of 2 is sufficient, but you can try 1 if your system can handle it for your image size.

Let me know if you have any questions, happy to clarify or provide more information!

Cheers,

Talmo
