### ISSUE TITLE
_make_labeled_frames_from_generator: IndexError: list index out of range

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#578]
Hello
So we're trying to use a trained NN on new videos.  We made an .slp package using the new videos but when training from the command line, we get this weird error that there are no files.

Is there something obvious we're doing wrong here?

Thanks so much!

<img width="1384" alt="terminal_error" src="https://user-images.githubusercontent.com/4267452/128040573-3904adb3-13a4-4d8b-aebd-e87557afcf7a.png">

**Comment by catubc** [comment]
Update:
Seems we can predict on each video and then merge them using the GUI.  We'll update if this works all the way through, but would be good to know why we can't train on exported .pkg.slp files at some point.

**Comment by talmo** [comment]
Hey @catubc,

It looks like this error comes up during inference right?

Did you mean that you can't _predict_ on exported .pkg.slp files at some point?

**Comment by catubc** [comment]
Yes, that's correct. So we made a project with multiple videos and about 100 labeled frames. Exported the project and trained an NN. But when we export the project as a .pkg.slp to run inference on the (all) original vids, we get this error suggesting there's no vids in the list or something along those lines.

**Comment by talmo** [comment]
Right, so I think exporting the entire project for inference might be a little hairy. Usually the idea is to just export `.pkg.slp` files for a subset of frames, typically for evaluation or inference on suggestions.

The problem here might be that the original videos are not being referenced correctly or are not accessible from the environment where you're calling `sleap-track`.

You can check this by:
```py
import sleap
labels = sleap.load_file("exported.pkg.slp")
print(labels.videos)
print([video.filename for video in labels.videos])
```

Let me know what you get.

You may get an error, or the filenames refer to the original labels file (`.slp`), or they may refer to the original video files (`.mp4`). Depending on which one you get, we can troubleshoot further.

**Comment by catubc** [comment]
Ok, the issue here seems to be that we forgot to define the tracks in the new dataset.  Sleap is not yet smart enough to automatically use the tracks from the Model on the prediction file.  

The solution is to either ensure you have the tracks in the prediction file (even if no labels are made) or follow the steps in the attached image to copy the tracks from the model to the file to be processed.

Thanks!
![cohort2_sleap_on_cohort3_data](https://user-images.githubusercontent.com/4267452/133246675-3889ce4f-e460-4bfb-91ae-f2d3208fefd3.png)
