### ISSUE TITLE
unet

### ISSUE THREAD

**Issue by D19CrMei** [murthylab/sleap#607]
hello，
I tried your SLEAP code and successfully output the key points. However, as for the statement that UNET was replaced by HRnet in your paper, I saw hrnet.py in the code. How to change it? Where should I modify the network structure?

**Comment by talmo** [comment]
Hi @D19CrMei,

We actually do not currently support HRNet. We previously implemented it and you're welcome to try and use it yourself, but it is not presently integrated in SLEAP. We welcome contributions but do not plan to add it back in since we were not able to get consistent performance using (our implementation of) the architecture.
