### ISSUE TITLE
The 'wheel>=0.26' distribution was not found and is required by tensorflow

### ISSUE THREAD

**Issue by Chriss12138** [murthylab/sleap#614]
Hi,

I followed everything through the tutorial, but when I tried to do `(sleap) C:\Users\chris\> sleap-label`, the following exceptions and errors occurred. I'm new to programming, could anyone help me fix this?

`pkg_resources.ContextualVersionConflict: (numpy 1.19.2 (c:\users\chrisch.psych\.conda\envs\sleap\lib\site-packages), Requirement.parse('numpy<1.19.0,>=1.18.1'), {'sleap'})`
`pkg_resources.DistributionNotFound: The 'wheel>=0.26' distribution was not found and is required by tensorflow`

Thanks,

Chris

**Comment by escobarg** [comment]
I am also getting this issue when trying to install any updates!

**Comment by talmo** [comment]
Hey guys,

Sorry about the delay! We're in the process of updating SLEAP to v1.2.0 which will fix this issue. I'll update this thread as soon as we have a workaround.

**Comment by abdelrahman-0** [comment]
I ran into the same issue on Windows 10 Home. Fixed it by installing the correct .whl file in sleap's conda environment. You can find your correct .whl file under this link:
https://pypi.org/project/tensorflow/2.3.1/#files
(in my case I downloaded tensorflow-2.3.1-cp36-cp36m-win_amd64.whl)

**Comment by talmo** [comment]
BTW, as a general workaround for now, you should be able to fix this by just installing tensorflow again, e.g.:

```
conda create -y -n sleap_v1.1.5 -c sleap sleap=1.1.5
conda activate sleap_v1.1.5
pip install tensorflow==2.3.1
```

**Comment by stednitzs** [comment]
This is also fixable by downgrading to numpy 1.18

**Comment by talmo** [comment]
Hi all,

This should now be fixed in [SLEAP v1.2.0](https://github.com/murthylab/sleap/releases/tag/v1.2.0)! Head over to the [installation page](https://sleap.ai/installation.html) for instructions on setting it up.

Thanks for all the reports and workarounds. Please feel free to open a new issue if you're having trouble installing the new version.

Cheers,

Talmo

**Comment by talmo** [comment]
Hey @kylethieringer,

Did you run into this in a fresh conda environment?

**Comment by kylethieringer** [comment]
@talmo yes this was a fresh environment

**Comment by kylethieringer** [comment]
hey @talmo I think I know what the problem was because I ran into the same error after a reboot so had to do a little troubleshooting. When I originally setup the new environment i did not specify the newest sleap version 1.2.2 so it defaulted to 1.1.5. Now that I installed a fresh environment with 1.2.2 there were no issues. Sorry about that!
