### ISSUE TITLE
No node/edges in predicted video even after a successful inference

### ISSUE THREAD

**Issue by Sai-Priyanka** [murthylab/sleap#629]
Hello Team,

Thank you for developing a this framework, which is simple to use and can be adaptable with different dataset formats.
Mine a multi-animal project for fish tracking. I have labelled, train (top-down approach), run inference successfully, but while loading the predictions in GUI to check the labels, see to have an issue where I am not able to see any labels!!?
But prediction file showing the tracking details with score. I am not sure what might be the problem??
Any help would be so great! thanks a lot in advance!!

![image](https://user-images.githubusercontent.com/47540873/149569668-b58384f4-e3c0-4360-9899-5472b64d40c9.png)

**Comment by Sai-Priyanka** [comment]
Hi again,

Seems like centered-instance prediction problem, predictions file of centered-instance doesn't have the labels. 
![image](https://user-images.githubusercontent.com/47540873/149573612-19d048bb-2eff-4cb3-bd9d-b76c07340ac4.png)
Sorry for not looking into this before.
Below is the the evaluation metrics for centered-instance. Visualization images looked fine while training. I am not sure why nothing is learned by model?? any suggestions might be highly appreciated. Thanks a lot!!
![image](https://user-images.githubusercontent.com/47540873/149573569-62a1a23b-1df8-48ab-85b6-9d9d811e79ea.png)

**Comment by talmo** [comment]
Hi @Sai-Priyanka,

That's pretty odd considering the visualization images were looking ok and that you're getting tracks in the GUI timeline. 🤔

Do you mind sharing a link to:
- Both the centroid and centered instance model folders
- The SLP project file that you're labeling from
- (Optionally) A sample video for testing

Thanks!!

Talmo

**Comment by Sai-Priyanka** [comment]
Hi @talmo 

Thank you so much for quick reply!!

I have just send an email with complete SLP project attached. Thanks a lot!!

**Comment by talmo** [comment]
Hi @Sai-Priyanka,

So I'm not sure what was going on, but it seemed like you had multiple skeletons in your project file. This shouldn't happen in newer SLEAP versions (>1.1.3 I think), but perhaps this is indicative of a bug.

Do you mind sharing a bit more about your setup?
- What version of SLEAP are you using to label?
- What is your exact labeling → training → merging procedure (assuming you use Colab every time)?
- I see you have tracks assigned to the animals -- were you able to get reasonable predictions in past rounds of labeling/training?

In any case, I merged all of the skeletons and updated them in the training job package. I also updated the skeleton such that all of the nodes were connected and form a tree (a requirement for bottom-up models).

I also noticed you were using a top-down model, but these animals vary quite a lot in scale, so you'd actually do better using a bottom-up model instead. I went ahead and trained one to verify that everything is working and it seems to be working decently:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/3187454/149865367-7b534508-ca2b-4f99-8de4-adbfac6b1904.png">


I'm emailing you all of the files, but let me know if you have any issues with them. Also, when you get a chance let me know about the questions above so we can make sure this doesn't happen again.

Cheers,

Talmo

**Comment by Sai-Priyanka** [comment]
Dear Talmo,

Thank you so much for looking into my issue and correcting it!

Below are the versions and steps I followed:

- Sleap V1.1.5 for labelling
- Created project → Added all nodes → designed skeleton → saved the skeleton and project → continued with labelling of manual added frames → save
- Predit → Run Inference → Given all need parameter inputs for top-down approach (it doesn't give me an option to select "anchor part") → export training job package
- Uploaded package to drive → accessed in colab and trained model with centroid.json & pkg → trained again with centered_instance.json & pkg → done
- Run Inference on test video (colab) → imported them in GUI to see the results

I have already tried bottom-up approach in DeepLabCut, I wanted to try with top_down approach. 
Actually I have a dataset with high density fishes (around 25-30 fish) in a frame. Due to the high density and lot of interaction between fish, results are not so good with tracking. So I wanted to test with top-down approach where identities are defined first and then key points ( which may avoid identity switching in tracking) is my thought.

Please let me know your thoughts about it, what approach can be better??

Many thanks,
Sai

**Comment by talmo** [comment]
Hi @Sai-Priyanka,

Thanks for the info.

So you'll definitely want to go to Predict → Run **Training**, not inference when you're generating the files for upload to Colab. Not totally sure how it even worked otherwise, but I'll look into it.

For inference, you can try just running it locally. It's slower without a GPU, but for testing purposes it's more convenient than uploading to Colab every time.

Re: bottom-up vs top-down: The top-down approach actually doesn't "identify" the individuals such that it would help with the tracking -- it just finds the centroids to locate the animals before cropping around them to pass on to the centered instance model.

Part of the issue with your data in particular is that the fish can vary quite drastically in terms of scale since it's a "side view". For close fish, the enclosing bounding box can be up to 512 x 512 pixels it seems, whereas when they are far I'd guess it'll go down to 64 x  64. This makes it tricky because the whole point of the top-down approach is that centered crops serve as a spatial prior for the second stage -- therefore if the crops cover most of the frame, you're going to have a lot of animals in the background.

Bottom-up has its own issues, but it can at least deal with scale variability a bit better. It is important that you have a skeleton that forms a tree though.

In any case, neither of these approaches resolve the problem of identity switching. Because your data is a bit different than most lab settings in that you can have a variable (and high) number of animals, some of which will appear and disappear arbitrarily, it makes the tracking problem considerably more difficult. SLEAP will definitely work, but if I had to guess, it probably won't be super accurate. I think the flow shift algorithm will do reasonably well, but it won't get you all the way there since there's nothing built-in to explicitly deal with animals disappearing -- and especially **re-**appearing.

Give it a go and see how it's doing. If you want to try some more specialized alternatives for dealing with collectives, I'd recommend checking out [idTracker.ai](https://idtracker.ai) or [TRex](https://github.com/mooch443/trex). If you need pose in addition to identities, you can combine SLEAP with the outputs of either one with some custom code (happy to help if you get to that step).

Closing this issue for now but let me know if there's anything else I can help with.

Cheers,

Talmo
