### ISSUE TITLE
tracking animal and apparatus

### ISSUE THREAD

**Issue by aereimer** [murthylab/sleap#673]
Dear SLEAP community,

I’m running some rats on plus maze and open-field tests. Can I use SLEAP to "track" both the animal and the apparatus (elevated plus maze, for example, for posterior ROI analysis)? In that case, SLEAP should be configured as a multi-animal experiment [1->subject; 2-> EPM]?

Thanks!

**Comment by talmo** [comment]
Hi @aereimer,

Great question! We generally recommend training separate models for tracking things with very different skeletons. You'd run the inference separately and then combine the coordinates in your own analysis afterwards.

Although you _could_ do it using a single model, it'll be much less efficient for labeling since you'd have to include all of the nodes for both objects in all your labels.

For your specific case, it would be pretty easy to train a quick model that can predict the EPM landmarks that define the ROI since that is (presumably) static for most or all of each video. The model could then be trained from 1-2 frames from each session and it would probably be sufficient.

Let me know what you think or if you have any questions!

Cheers,

Talmo

**Comment by aereimer** [comment]
Hey Talmo, 

Your suggestion makes a lot of sense! - I already have a good model for the subject and will make a separated one for the EPM.

thanks!

**Comment by talmo** [comment]
Closing this issue but feel free to reply or create another one if you run into any problems!
