### ISSUE TITLE
Inference Result problem: Instances were predicted on 0 frames (0 frames with no instances found)

### ISSUE THREAD

**Issue by Leorio183** [murthylab/sleap#722]
Hi, everyone, I am new to SLEAP. I just encountered a problem like below:
I labeled 30 frames, and I just want to track only one mouse, so I followed the tutorial, but it get this result in the inference stage after training. How can I solve this problem, and where can I find more detailed tutorials.
Thanks to everyone.
![image](https://user-images.githubusercontent.com/105135795/167277659-f3242f69-52c1-461d-9981-6a5c976f6cc1.png)

**Comment by Leorio183** [comment]
This is how I labeled.
![image](https://user-images.githubusercontent.com/105135795/167277840-8a16e74a-034a-4ac2-aae0-44df9dc3f165.png)

**Comment by KennyTC** [comment]
@Leorio183  did you find the solution? I met the same problem and did not know  how to solve.

**Comment by roomrys** [comment]
Hi @KennyTC,

Did you set a "Predict On" method? The message shows that inference was attempted on 0 frames, likely due to having "Predict On" set to "nothing". 

I realize this is a bit confusing and we should likely refrain from showing the message in the first place if "Predict On" is set to "nothing".

Let me know if this helps!

Thanks,
Liezl
